### ISSUE TITLE
.find(query, [indexName]) to retrieve multiple models

### ISSUE THREAD

**Issue by paglias** [AmpersandJS/ampersand-collection#51]
I've just jumped in Ampersand and I really like it.

One thing that I miss is the ability to retrieve more than one method using an index.

For example retrieving all the models that match a query not a single one.

I gave a look to the code and would like to make a pull request but first wanted to hear what do you about it

**Comment by prust** [comment]
@paglias,

The docs state:

> Note that get will only ever return a single model, so the values of these indexes should be unique across the models in the collection

I'm assuming that you don't want to change that (correct me if I'm wrong), but that you want to pass in an array of IDs as your `query` and get multiple models back, like this:

```javascript
var models = coll.find([1, 5, 7]);
// would return 3 models
```

I'm not a fan of the name `find()` since this is already a method in Underscore/Backbone and it returns a single model.

Personally I would prefer to take the concept a bit further, using underscore/backbone's `where()` API, but having a special exception if it is passed an array. Instead of looking for that same array on the models it is searching, it would match any model that has any of the values in the array. For example:

```javascript
var models = coll.where({id: [1, 5, 7]});
// would return 3 models
```

But this is opinionated and not 100% obvious and it makes it impossible to use `where()` to search for an array reference (though over the course of years of backbone programming I've never needed this). Implementing this kind of smart query engine that uses indexes wouldn't be hard, but seems a bit beyond the scope of ampersand-collection... it's something that could easily be implemented on top of ampersand-collection using the existing `.get()` and `.indexes` APIs.

**Comment by paglias** [comment]
@prust so I think I missed the part where it says that index should be considered unique :)

My idea was to implement the equivalent of Backbone's `where` but using indexes for fast access.

Indexes would be moved from single references to an array of references with `.get()` returning the first one only.

As for a standard where, personally I'm using `collection.filter` to achieve the same result but I think it would be a valuable addition too.

Lastly, I don't have any preference for the name, I said `find()` because I noticed it's used sometimes to distinguish from returing a single item (get) or multiple (find)

**Comment by prust** [comment]
@paglias:

> Indexes would be moved from single references to an array of references

Ah, I see. That would make indexes more valuable and would need to be an internal change to ampersand-collection. Perhaps that should be a separate (and more important) issue, with the .find()/.where() method being a secondary issue that could be implemented separately as a mixin...

**Comment by pgilad** [comment]
Use `collection.filter(model => _.includes([1, 2, 3], model.id);`
